---
title: "Data Science Methods for Vision Science Applications"
subtitle: "applied statistics, simulation and modeling with an introduction to machine learning using the Python programming language"
author: with Course Instructor, Bonnie Cooper bcooper@sunyopt.edu
#output: markdowntemplates::bulma
output:
  prettydoc::html_pretty:
    theme: architect
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description
&nbsp;&nbsp;&nbsp;&nbsp;Data Science Methods for Vision Science Applications will provide students with an overview of current data science tools and methodology while using datasets from various fields of vision science.   
&nbsp;&nbsp;&nbsp;&nbsp;Data Science is a fast growing inter-disciplinary collection of algorithms, tools and technology used to gain insights from the increasingly large and complex data generated in this digital age. Vision science and visual neuroscience have also seen a rapid increase in the volume of data generated. (e.g. neural recording arrays, imaging data, etc.) This creates a new challenge for today's graduate student: learning the field is complicated by increasingly complex data. The aim of this course is to introduce students to some of the tools and techniques from data science to meet the growing demands of today's vision science.

## Why Python?
&nbsp;&nbsp;&nbsp;&nbsp;Unlike Matlab, Python is an open-source programming language known for it's readability and extensive community support. The introduction of numeric and scientific libraries such as the `scipy` stack (e.g. `numpy`, `pandas`, `scikit-learn`, etc.) have lead to an increased application of [python in neuroscience](https://www.frontiersin.org/articles/10.3389/fninf.2015.00011/full) and [psychophysics](https://www.psychopy.org/). Additionally, Python is a generalized programming language and can be utilized for diverse research applications (from experimental control to data analysis/visualization); this is an advantage over languages more specific for statistical analysis (e.g. R). Python is used extensively in industry. Therefore, exposure to the language now will be beneficial for students who may be interested in career opportunities outside of academia.

## Course Requirements
&nbsp;&nbsp;&nbsp;&nbsp;This course will be designed for students with all levels of programming skills. However, the course will be python intensive. Students with no previous python or, more generally, programming experience will be asked to complete online python tutorials before the class starts.

## Course Objectives
&nbsp;&nbsp;&nbsp;&nbsp;Students will build a hypothesis driven analysis of a dataset using data science tools using python. Upon completion, students will gain confidence using code driven approaches in solving research questions. It is hoped that experience computing with python and using git for version control will become powerful tools to be used to enhance future research endeavors. 

## Course Evaluation
&nbsp;&nbsp;&nbsp;&nbsp;The course will be divided into learning modules. Each module will be accompanied by a project template (jupyter notebooks) that will walk through the relevant code, concepts and methods covered in the module. Students will be given complete and commented code to be used to interpret incomplete code and/or generate new code to generate insights. 
Students will use a dataset of their choosing to build a hypothesis driven data science project. This final project will incorporate modules covered in the course, results will be summarized in a report and shared in a brief oral presentation.

## Course Outline

| **Module**                                | **Objectives**                                                                                                                                    |
|-------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
|         Data Access & Manipulation        | loading a variety of data into the python environment,  `numpy` arrays & `pandas` dataframes, and an into to  version control with git            |
| Exploratory Data Analysis & Visualization | data inspection, data cleaning, summary statistics and basic visualizations with `Matplotlib` & `Seaborn`                                         |
|    Probability Basics & Simulating Data   | random numbers in python, probability review & simulating data                                                                                    |
|           Experimental Design             | an introduction to `psychopy` for designing and implementing psychophysical experiments                                                           |
|      Linear & GLM Regression Methods      | `sklearn` linear regression, multiple regression and logistic regression models, evaluation and validation                                        |
|        Machine Learning: Supervised       | basic supervised learning approaches for numeric data: regression & decision trees and categorical data: classification/categorization (e.g. kNN) |
|       Machine Learning: Unsupervised      | basic unsupervised learning approaches for numeric data: dimensionality reduction (e.g PCA) and categorical data: clustering (e.g. K-mean)        |
|               Data Narratives              | students will organize a project, prepare a report and give a brief talk to present their findings                                                |

## Course Instructor
&nbsp;&nbsp;&nbsp;&nbsp;Dr. Cooper is a post-doctoral researcher at SUNY College of Optometry in the lab of Prof. Robert M McPeek. Bonnie has experienced the graduate program at SUNYOpt having received her PhD from the program under Prof. Barry B Lee; this gives her first-hand understanding of the needs faced by the program's PhD candidates. Additionally, Bonnie is currently pursuing a Master's of Science in Data Science at CUNY with a focus on machine learning making her uniquely qualified to instruct data science methods to vision science students.

